---
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
      - any-glob-to-any-file: ".gitignore"

area/devcontainer:
  - changed-files:
      - any-glob-to-any-file: ".devcontainer/**/*"
      - any-glob-to-any-file: "requirements.txt"

area/templates/golang:
  - changed-files:
      - any-glob-to-any-file: "golang/**/*"
