---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: {{{{ cookiecutter.project_name }}}}

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{{{ .ProjectName }}}}"
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}/cmd.version={{{{ .Version }}}}

archives:
  - format: tar.gz
    name_template: "{{{{ .ProjectName }}}}_{{{{ .Os }}}}_{{{{ .Arch }}}}"

checksum:
  disable: false
  name_template: "checksums.txt"

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Patches"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "CI"
      regexp: ".*ci.*"
      order: 998
    - title: Others
      order: 999

nfpms:
  - homepage: https://github.com/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}
    maintainer: {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>
    description: {{ cookiecutter.description }}
    file_name_template: "{{{{ .ProjectName }}}}_{{{{ .Os }}}}_{{{{ .Arch }}}}"
    license: MIT
    formats: [deb, apk, rpm]

dockers:
  - image_templates:
      - "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{{{ .Date }}}}"
      - "--label=org.opencontainers.image.title={{{{ .ProjectName }}}}"
      - "--label=org.opencontainers.image.revision={{{{ .FullCommit }}}}"
      - "--label=org.opencontainers.image.version={{{{ .Version }}}}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.authors={{{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"
      - "--label=org.opencontainers.image.description={{ cookiecutter.description }}"
  - image_templates:
      - "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{{{ .Date }}}}"
      - "--label=org.opencontainers.image.title={{{{ .ProjectName }}}}"
      - "--label=org.opencontainers.image.revision={{{{ .FullCommit }}}}"
      - "--label=org.opencontainers.image.version={{{{ .Version }}}}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.authors={{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"
      - "--label=org.opencontainers.image.description={{ cookiecutter.description }}"

docker_manifests:
  - name_template: "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}"
    image_templates:
      - "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}-amd64"
      - "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}-arm64v8"

  - name_template: "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:latest"
    image_templates:
      - "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}-amd64"
      - "ghcr.io/{{ cookiecutter.author_username }}/{{{{ .ProjectName }}}}:v{{{{ .Version }}}}-arm64v8"
