---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: {{ cookiecutter.project_name }}

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{ {{ }} .ProjectName {{ }} }}"
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/{{ cookiecutter.author_username }}/{{ {{ }} .ProjectName {{ }} }}/cmd.version={{ {{ }} .Version {{ }} }}

archives:
  - format: tar.gz
    name_template: "{{ {{ }} .ProjectName {{ }} }}_{{ {{ }} .Os {{ }} }}_{{ {{ }} .Arch {{ }} }}"

checksum:
  disable: false
  name_template: "checksums.txt"

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Patches"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "CI"
      regexp: ".*ci.*"
      order: 998
    - title: Others
      order: 999
